
"use client"
import { Geist, Geist_Mono, Nabla } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import Head from "next/head";
import { usePathname } from "next/navigation";
import ChatbotWidget from '../components/ChatbotWidget';







// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "CollegeMangementSystem",
//   description: "Generated by create next app",
  
  
// };

export default function RootLayout({ children }) {
  const pathName = usePathname()
  return (
    <html lang="en">
       <link rel="icon" href="/favicon.ico" />
      <body
      
        className={`antialiased`}
      >
       <Head>
        <title>CollegeMangementSystem</title>
        <meta name="descripton">
        Generated by create next app
        </meta>
       </Head>
        <Provider store={store}>
         
         {!pathName.includes("admin")&&<Navbar /> }           
        
        {children}
        {(!pathName.includes("preview")&&!pathName.includes("admin")) && <Footer />}
        <ChatbotWidget /> 
        </Provider>
        
        
        
      </body>
    </html>
  );
}


